// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: prober.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//报告localIP
// ProberAgentIpReport
type ProberAgentIpReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ProberAgentIpReportRequest) Reset() {
	*x = ProberAgentIpReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberAgentIpReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberAgentIpReportRequest) ProtoMessage() {}

func (x *ProberAgentIpReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberAgentIpReportRequest.ProtoReflect.Descriptor instead.
func (*ProberAgentIpReportRequest) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{0}
}

func (x *ProberAgentIpReportRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ProberAgentIpReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
}

func (x *ProberAgentIpReportResponse) Reset() {
	*x = ProberAgentIpReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberAgentIpReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberAgentIpReportResponse) ProtoMessage() {}

func (x *ProberAgentIpReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberAgentIpReportResponse.ProtoReflect.Descriptor instead.
func (*ProberAgentIpReportResponse) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{1}
}

func (x *ProberAgentIpReportResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

// Targets
type Targets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PingCmd      string `protobuf:"bytes,1,opt,name=ping_cmd,json=pingCmd,proto3" json:"ping_cmd,omitempty"`
	TargetRegion string `protobuf:"bytes,2,opt,name=target_region,json=targetRegion,proto3" json:"target_region,omitempty"`
	//ip
	TargetIp string `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
}

func (x *Targets) Reset() {
	*x = Targets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Targets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Targets) ProtoMessage() {}

func (x *Targets) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Targets.ProtoReflect.Descriptor instead.
func (*Targets) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{2}
}

func (x *Targets) GetPingCmd() string {
	if x != nil {
		return x.PingCmd
	}
	return ""
}

func (x *Targets) GetTargetRegion() string {
	if x != nil {
		return x.TargetRegion
	}
	return ""
}

func (x *Targets) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

type TargetConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets   []*Targets `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	SliceName string     `protobuf:"bytes,2,opt,name=slice_name,json=sliceName,proto3" json:"slice_name,omitempty"`
}

func (x *TargetConfig) Reset() {
	*x = TargetConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetConfig) ProtoMessage() {}

func (x *TargetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetConfig.ProtoReflect.Descriptor instead.
func (*TargetConfig) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{3}
}

func (x *TargetConfig) GetTargets() []*Targets {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *TargetConfig) GetSliceName() string {
	if x != nil {
		return x.SliceName
	}
	return ""
}

// The request message containing the worker_name.
type ProberTargetsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//agent探测轮数
	AgentRound    int64  `protobuf:"varint,1,opt,name=agent_round,json=agentRound,proto3" json:"agent_round,omitempty"`
	LocalIp       string `protobuf:"bytes,2,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalNodeName string `protobuf:"bytes,3,opt,name=local_node_name,json=localNodeName,proto3" json:"local_node_name,omitempty"`
	LocalVlanId   int64  `protobuf:"varint,4,opt,name=local_vlan_id,json=localVlanId,proto3" json:"local_vlan_id,omitempty"`
}

func (x *ProberTargetsGetRequest) Reset() {
	*x = ProberTargetsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberTargetsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberTargetsGetRequest) ProtoMessage() {}

func (x *ProberTargetsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberTargetsGetRequest.ProtoReflect.Descriptor instead.
func (*ProberTargetsGetRequest) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{4}
}

func (x *ProberTargetsGetRequest) GetAgentRound() int64 {
	if x != nil {
		return x.AgentRound
	}
	return 0
}

func (x *ProberTargetsGetRequest) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *ProberTargetsGetRequest) GetLocalNodeName() string {
	if x != nil {
		return x.LocalNodeName
	}
	return ""
}

func (x *ProberTargetsGetRequest) GetLocalVlanId() int64 {
	if x != nil {
		return x.LocalVlanId
	}
	return 0
}

// The response message containing the ProberTargets
type ProberTargetsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetConfigs []*TargetConfig `protobuf:"bytes,1,rep,name=target_configs,json=targetConfigs,proto3" json:"target_configs,omitempty"`
}

func (x *ProberTargetsGetResponse) Reset() {
	*x = ProberTargetsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberTargetsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberTargetsGetResponse) ProtoMessage() {}

func (x *ProberTargetsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberTargetsGetResponse.ProtoReflect.Descriptor instead.
func (*ProberTargetsGetResponse) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{5}
}

func (x *ProberTargetsGetResponse) GetTargetConfigs() []*TargetConfig {
	if x != nil {
		return x.TargetConfigs
	}
	return nil
}

// ProberResultOne
type ProberResultOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricName   string `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	SourceRegion string `protobuf:"bytes,2,opt,name=source_region,json=sourceRegion,proto3" json:"source_region,omitempty"`
	TargetRegion string `protobuf:"bytes,3,opt,name=target_region,json=targetRegion,proto3" json:"target_region,omitempty"`
	SliceName    string `protobuf:"bytes,4,opt,name=slice_name,json=sliceName,proto3" json:"slice_name,omitempty"`
	TimeStamp    int64  `protobuf:"varint,5,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Value        int32  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProberResultOne) Reset() {
	*x = ProberResultOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberResultOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberResultOne) ProtoMessage() {}

func (x *ProberResultOne) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberResultOne.ProtoReflect.Descriptor instead.
func (*ProberResultOne) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{6}
}

func (x *ProberResultOne) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ProberResultOne) GetSourceRegion() string {
	if x != nil {
		return x.SourceRegion
	}
	return ""
}

func (x *ProberResultOne) GetTargetRegion() string {
	if x != nil {
		return x.TargetRegion
	}
	return ""
}

func (x *ProberResultOne) GetSliceName() string {
	if x != nil {
		return x.SliceName
	}
	return ""
}

func (x *ProberResultOne) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ProberResultOne) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// The request message of proberesult
type ProberResultPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProberResults []*ProberResultOne `protobuf:"bytes,1,rep,name=prober_results,json=proberResults,proto3" json:"prober_results,omitempty"`
}

func (x *ProberResultPushRequest) Reset() {
	*x = ProberResultPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberResultPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberResultPushRequest) ProtoMessage() {}

func (x *ProberResultPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberResultPushRequest.ProtoReflect.Descriptor instead.
func (*ProberResultPushRequest) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{7}
}

func (x *ProberResultPushRequest) GetProberResults() []*ProberResultOne {
	if x != nil {
		return x.ProberResults
	}
	return nil
}

type ProberResultPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessNum int32 `protobuf:"varint,1,opt,name=success_num,json=successNum,proto3" json:"success_num,omitempty"`
}

func (x *ProberResultPushResponse) Reset() {
	*x = ProberResultPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProberResultPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProberResultPushResponse) ProtoMessage() {}

func (x *ProberResultPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProberResultPushResponse.ProtoReflect.Descriptor instead.
func (*ProberResultPushResponse) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{8}
}

func (x *ProberResultPushResponse) GetSuccessNum() int32 {
	if x != nil {
		return x.SuccessNum
	}
	return 0
}

//完成本轮ping后,agent发起切换vlan请求
type RefreshVlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalIp       string `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalVlanId   int64  `protobuf:"varint,2,opt,name=local_vlan_id,json=localVlanId,proto3" json:"local_vlan_id,omitempty"`
	LocalNodeName string `protobuf:"bytes,3,opt,name=local_node_name,json=localNodeName,proto3" json:"local_node_name,omitempty"`
	AgentRound    int64  `protobuf:"varint,4,opt,name=agent_round,json=agentRound,proto3" json:"agent_round,omitempty"`
}

func (x *RefreshVlanRequest) Reset() {
	*x = RefreshVlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshVlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVlanRequest) ProtoMessage() {}

func (x *RefreshVlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVlanRequest.ProtoReflect.Descriptor instead.
func (*RefreshVlanRequest) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshVlanRequest) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *RefreshVlanRequest) GetLocalVlanId() int64 {
	if x != nil {
		return x.LocalVlanId
	}
	return 0
}

func (x *RefreshVlanRequest) GetLocalNodeName() string {
	if x != nil {
		return x.LocalNodeName
	}
	return ""
}

func (x *RefreshVlanRequest) GetAgentRound() int64 {
	if x != nil {
		return x.AgentRound
	}
	return 0
}

type RefreshVlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeedWait   bool  `protobuf:"varint,1,opt,name=need_wait,json=needWait,proto3" json:"need_wait,omitempty"`
	NeedSwitch bool  `protobuf:"varint,2,opt,name=need_switch,json=needSwitch,proto3" json:"need_switch,omitempty"`
	NewRound   int64 `protobuf:"varint,3,opt,name=new_round,json=newRound,proto3" json:"new_round,omitempty"`
}

func (x *RefreshVlanResponse) Reset() {
	*x = RefreshVlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshVlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVlanResponse) ProtoMessage() {}

func (x *RefreshVlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVlanResponse.ProtoReflect.Descriptor instead.
func (*RefreshVlanResponse) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshVlanResponse) GetNeedWait() bool {
	if x != nil {
		return x.NeedWait
	}
	return false
}

func (x *RefreshVlanResponse) GetNeedSwitch() bool {
	if x != nil {
		return x.NeedSwitch
	}
	return false
}

func (x *RefreshVlanResponse) GetNewRound() int64 {
	if x != nil {
		return x.NewRound
	}
	return 0
}

//切换成功通知
type NotifyVlanSwitchedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VlanId     int32  `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	SwitchTime string `protobuf:"bytes,2,opt,name=switch_time,json=switchTime,proto3" json:"switch_time,omitempty"`
}

func (x *NotifyVlanSwitchedRequest) Reset() {
	*x = NotifyVlanSwitchedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyVlanSwitchedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyVlanSwitchedRequest) ProtoMessage() {}

func (x *NotifyVlanSwitchedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyVlanSwitchedRequest.ProtoReflect.Descriptor instead.
func (*NotifyVlanSwitchedRequest) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyVlanSwitchedRequest) GetVlanId() int32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *NotifyVlanSwitchedRequest) GetSwitchTime() string {
	if x != nil {
		return x.SwitchTime
	}
	return ""
}

type NotifyVlanSwitchedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *NotifyVlanSwitchedResponse) Reset() {
	*x = NotifyVlanSwitchedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prober_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyVlanSwitchedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyVlanSwitchedResponse) ProtoMessage() {}

func (x *NotifyVlanSwitchedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prober_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyVlanSwitchedResponse.ProtoReflect.Descriptor instead.
func (*NotifyVlanSwitchedResponse) Descriptor() ([]byte, []int) {
	return file_prober_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyVlanSwitchedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_prober_proto protoreflect.FileDescriptor

var file_prober_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x2c, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x22, 0x3c, 0x0a, 0x1b, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x66,
	0x0a, 0x07, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x6d, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x49, 0x70, 0x22, 0x54, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x73, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xa1, 0x01, 0x0a,
	0x17, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x49, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x56, 0x6c, 0x61, 0x6e, 0x49, 0x64,
	0x22, 0x53, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0e,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0xd0, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x6e, 0x65,
	0x52, 0x0d, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0x3b, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x9c, 0x01, 0x0a,
	0x12, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x56, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x70, 0x12, 0x22,
	0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x56, 0x6c, 0x61, 0x6e,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x70, 0x0a, 0x13, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x56, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x57, 0x61, 0x69, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x55, 0x0a,
	0x19, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x56, 0x6c, 0x61, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6c,
	0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x6c, 0x61,
	0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x1a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x56, 0x6c,
	0x61, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x70, 0x0a, 0x13,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x59, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x62,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x4f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x72, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x32, 0x64, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x50, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x4f, 0x0a, 0x0b, 0x56, 0x6c, 0x61, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x56, 0x6c, 0x61, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x56, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x56, 0x6c, 0x61, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x69, 0x0a, 0x10, 0x56, 0x6c, 0x61,
	0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x55, 0x0a,
	0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x56, 0x6c, 0x61, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x56,
	0x6c, 0x61, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x56, 0x6c,
	0x61, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prober_proto_rawDescOnce sync.Once
	file_prober_proto_rawDescData = file_prober_proto_rawDesc
)

func file_prober_proto_rawDescGZIP() []byte {
	file_prober_proto_rawDescOnce.Do(func() {
		file_prober_proto_rawDescData = protoimpl.X.CompressGZIP(file_prober_proto_rawDescData)
	})
	return file_prober_proto_rawDescData
}

var file_prober_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_prober_proto_goTypes = []interface{}{
	(*ProberAgentIpReportRequest)(nil),  // 0: pb.ProberAgentIpReportRequest
	(*ProberAgentIpReportResponse)(nil), // 1: pb.ProberAgentIpReportResponse
	(*Targets)(nil),                     // 2: pb.Targets
	(*TargetConfig)(nil),                // 3: pb.TargetConfig
	(*ProberTargetsGetRequest)(nil),     // 4: pb.ProberTargetsGetRequest
	(*ProberTargetsGetResponse)(nil),    // 5: pb.ProberTargetsGetResponse
	(*ProberResultOne)(nil),             // 6: pb.ProberResultOne
	(*ProberResultPushRequest)(nil),     // 7: pb.ProberResultPushRequest
	(*ProberResultPushResponse)(nil),    // 8: pb.ProberResultPushResponse
	(*RefreshVlanRequest)(nil),          // 9: pb.RefreshVlanRequest
	(*RefreshVlanResponse)(nil),         // 10: pb.RefreshVlanResponse
	(*NotifyVlanSwitchedRequest)(nil),   // 11: pb.NotifyVlanSwitchedRequest
	(*NotifyVlanSwitchedResponse)(nil),  // 12: pb.NotifyVlanSwitchedResponse
}
var file_prober_proto_depIdxs = []int32{
	2,  // 0: pb.TargetConfig.targets:type_name -> pb.Targets
	3,  // 1: pb.ProberTargetsGetResponse.target_configs:type_name -> pb.TargetConfig
	6,  // 2: pb.ProberResultPushRequest.prober_results:type_name -> pb.ProberResultOne
	0,  // 3: pb.ProberAgentIpReport.ProberAgentIpReports:input_type -> pb.ProberAgentIpReportRequest
	4,  // 4: pb.GetProberTarget.GetProberTargets:input_type -> pb.ProberTargetsGetRequest
	7,  // 5: pb.PushProberResult.PushProberResults:input_type -> pb.ProberResultPushRequest
	9,  // 6: pb.VlanService.RefreshVlan:input_type -> pb.RefreshVlanRequest
	11, // 7: pb.VlanSwitchNotify.NotifyVlanSwitched:input_type -> pb.NotifyVlanSwitchedRequest
	1,  // 8: pb.ProberAgentIpReport.ProberAgentIpReports:output_type -> pb.ProberAgentIpReportResponse
	5,  // 9: pb.GetProberTarget.GetProberTargets:output_type -> pb.ProberTargetsGetResponse
	8,  // 10: pb.PushProberResult.PushProberResults:output_type -> pb.ProberResultPushResponse
	10, // 11: pb.VlanService.RefreshVlan:output_type -> pb.RefreshVlanResponse
	12, // 12: pb.VlanSwitchNotify.NotifyVlanSwitched:output_type -> pb.NotifyVlanSwitchedResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_prober_proto_init() }
func file_prober_proto_init() {
	if File_prober_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prober_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberAgentIpReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberAgentIpReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Targets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberTargetsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberTargetsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberResultOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberResultPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProberResultPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshVlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshVlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyVlanSwitchedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prober_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyVlanSwitchedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prober_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_prober_proto_goTypes,
		DependencyIndexes: file_prober_proto_depIdxs,
		MessageInfos:      file_prober_proto_msgTypes,
	}.Build()
	File_prober_proto = out.File
	file_prober_proto_rawDesc = nil
	file_prober_proto_goTypes = nil
	file_prober_proto_depIdxs = nil
}
